apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world
  description: Test project to test backstage component registation
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: artistweb
    github.com/project-slug: https://github.com/georgereal/spring-boot-hello-world
  tags:
    - java
spec:
  type: spring boot
  lifecycle: development
  owner: guest
  system: spring-boot-hello-world