apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-boot-hello-world
  description: A simple Spring Boot Hello World application with REST endpoints, Docker containerization, and CI/CD pipeline
  labels:
    java: spring-boot
    framework: spring
    language: java
    deployment: docker
    ci-cd: github-actions
  annotations:
    github.com/project-slug: georgereal/spring-boot-hello-world
    github.com/repo-url: https://github.com/georgereal/spring-boot-hello-world
    github.com/actions-workflow: ci-cd.yml
    github.com/actions-workflow-docker: docker-deploy.yml
    backstage.io/techdocs-ref: dir:.
    github.com/ci-status: enabled
    github.com/container-registry: ghcr.io/georgereal/spring-boot-hello-world
    github.com/deployment-url: https://georgereal.github.io/spring-boot-hello-world
    github.com/package-manager: maven
    github.com/java-version: "17"
    github.com/spring-boot-version: "3.2.0"
  tags:
    - java
    - spring-boot
    - rest-api
    - docker
    - github-actions
    - maven
    - microservice
spec:
  type: service
  lifecycle: production
  owner: georgereal
  system: spring-boot-hello-world
  dependsOn: []
  providesApis:
    - hello-world-api
  consumesApis: []
  subcomponentOf: []
  dependsOnResources: []
  providesResources: []
  consumesResources: []