apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-boot-hello-world
  description: spring-boot component
  labels:
    language: java
    framework: spring-boot
  annotations:
    github.com/project-slug: georgereal/spring-boot-hello-world
    backstage.io/managed-by-location: url:https://github.com/georgereal/spring-boot-hello-world/blob/main/catalog-info.yaml
spec:
  type: service
  lifecycle: production
  owner: georgereal
  system: spring-boot-hello-world
  providesApis:
    - spring-boot-hello-world-health-api
    - spring-boot-hello-world-info-api
    - spring-boot-hello-world-main-api
    - spring-boot-hello-world-webhooks-api
