apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: spring-boot-hello-world
  description: Spring Boot Hello World application system with CI/CD pipeline
  annotations:
    github.com/project-slug: georgereal/spring-boot-hello-world
    github.com/ci-status: enabled
    github.com/deployment-url: https://georgereal.github.io/spring-boot-hello-world
  tags:
    - spring-boot
    - microservices
    - ci-cd
    - docker
spec:
  owner: georgereal
  domain: microservices 