apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-boot-tekton-pipeline
  description: Tekton Pipeline for Spring Boot Hello World application build and test
  labels:
    tekton: pipeline
    ci-cd: tekton
    language: java
    framework: spring-boot
  annotations:
    # Tekton Pipeline Information
    tekton.dev/pipeline: spring-boot-build-test-pipeline
    tekton.dev/pipeline-run: spring-boot-build-test-run
    tekton.dev/namespace: default
    tekton.dev/cluster-url: https://kubernetes.default.svc
    tekton.dev/dashboard-url: http://localhost:9097
    tekton.dev/pipeline-description: "Simple pipeline to build and test Spring Boot application"
    tekton.dev/pipeline-tasks: "fetch-repository,maven-build,test-application"
    tekton.dev/maven-goals: "clean,package"
    tekton.dev/java-version: "11"
    tekton.dev/spring-boot-version: "2.7.18"
    # GitHub Repository Information
    github.com/project-slug: georgereal/spring-boot-hello-world
    github.com/repo-url: https://github.com/georgereal/spring-boot-hello-world
    # Backstage Integration
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/georgereal/spring-boot-hello-world
  links:
    - url: http://localhost:9097
      title: Tekton Dashboard
      icon: build
    - url: https://github.com/georgereal/spring-boot-hello-world
      title: GitHub Repository
      icon: github
    - url: http://localhost:9097/#/namespaces/default/pipelines/spring-boot-build-test-pipeline
      title: Pipeline Details
      icon: pipeline
    - url: http://localhost:9097/#/namespaces/default/pipelineruns
      title: Pipeline Runs
      icon: history
  tags:
    - tekton
    - pipeline
    - ci-cd
    - java
    - spring-boot
    - maven
    - kubernetes
spec:
  type: pipeline
  lifecycle: production
  owner: georgereal
  system: spring-boot-hello-world
  dependsOn:
    - component:spring-boot-hello-world