apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: spring-boot-build-test-run
  annotations:
    description: "Pipeline run for Spring Boot build and test"
spec:
  pipelineRef:
    name: spring-boot-build-test-pipeline
  
  params:
    - name: git-url
      value: "https://github.com/georgereal/spring-boot-hello-world.git"
  
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: pvc-792cb91622