apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello-world
  namespace: spring-boot-hello-world
  labels:
    app: spring-boot-hello-world
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-hello-world
  template:
    metadata:
      labels:
        app: spring-boot-hello-world
        version: v1
    spec:
      containers:
      - name: spring-boot-app
        image: ghcr.io/georgereal/spring-boot-hello-world:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      imagePullSecrets:
      - name: ghcr-secret
      securityContext:
        fsGroup: 1001