apiVersion: v1
kind: Service
metadata:
  name: spring-boot-hello-world-service
  namespace: spring-boot-hello-world
  labels:
    app: spring-boot-hello-world
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: spring-boot-hello-world