apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: spring-boot-hello-world-info-api
  description: info API for spring-boot-hello-world
  labels:
    component: spring-boot-hello-world
    language: java
    framework: spring-boot
  annotations:
    github.com/project-slug: georgereal/spring-boot-hello-world
    discovery.source: automated-scan
    discovery.timestamp: '2025-08-08T15:23:09.342Z'
spec:
  type: openapi
  lifecycle: production
  owner: georgereal
  system: spring-boot-hello-world
  definition:
    openapi: 3.0.0
    info:
      title: spring-boot-hello-world info API
      version: 1.0.0
      description: Auto-discovered API endpoints for spring-boot-hello-world
    servers:
      - url: https://github.com/georgereal/spring-boot-hello-world/api
        description: Component API server
    paths:
      /api/info:
        get:
          summary: GET /api/info
          description: Auto-discovered from Controller.java
          responses:
            '200':
              description: Successful response
              content:
                application/json:
                  schema:
                    type: object
          tags:
            - info
          x-discovery-source: code-scan
          x-discovery-file: Controller.java
          x-discovery-framework: spring-boot
